### ISSUE TITLE
Paging David.

### ISSUE THREAD

**Issue by mitm001** [jMonkeyEngine/wiki#104]
@davidB 

@davidB A fellow monkey, [8Keep123](https://hub.jmonkeyengine.org/u/8Keep123) and I have fully implemented the [Antora](https://docs.antora.org/antora/2.3/) project for the wiki using seperate repos to demonstrate it.
The docs
https://github.com/mitm001/docs.jmonkeyengine.org
The UI
https://github.com/mitm001/jme-ui/actions

The results,
https://mitm001.github.io/docs.jmonkeyengine.org/docs/documentation.html

I have written setup documentation for converting the wiki over. I can convert the wiki if you like the idea and it would only require a few minor things from your end to accomplish the task.

. We would need an github PAT with public_repo access.
. We would need a second repository for the user interface project.
. The PAT would need to be a secret on both so the workflow action between both repositories could communicate.

We would like continue onwards with what you have built. The initial setup would be done on a separate branch and using github actions so the wiki would not be affected until a merge was done. Other than the fact that a push to the master branch would trigger a build from the Travis setup, and a push to the Antora branch would build the Antora site to the gh-pages branch. 

If you go for it, then after the Antora branch is merged, I would reconfigure things to work on the master branch.

Please respond let me know what you think.

**Comment by davidB** [comment]
Good Job, I like what you did, my opinion is you and @Ali-RS are the real admin of the wiki. I'll promote your access, then you'll be free to go forward and make the jMonkeyDocumentation better (eg with Antora)

**Comment by davidB** [comment]
In your plan why having both github-actions and Travis ?

**Comment by mitm001** [comment]
> In your plan why having both github-actions and Travis ?

Hi David, only while I work on the branch setup. Once setup is complete, this all gets deleted,

https://github.com/mitm001/docs.jmonkeyengine.org/blob/master/setup-docs/antora_setup.adoc#cleanup

Thats the document for transition. I haven't proof read it but I think I have the transition down to around 12 commits.

**Comment by mitm001** [comment]
Basically, I would just be setting up things in the branch to make sure everything is working, then after rebase, I would just have a few keys to change on master to make it work there.

**Comment by davidB** [comment]
Instead of rebase or merge, if no commit, you could change the default
branch (or rename current branch into something like "master.old").
Anyway you're admin now. And you can remove my privileges I'm no longer a
active community member.

**Comment by davidB** [comment]
PS: I bookmarked Antora if I need this kind of tool in the future (currently I used the simple but enought mdbook, widely used in the Rust community)

**Comment by mitm001** [comment]
> Anyway you're admin now. And you can remove my privileges I'm no longer a
> active community member.

Just having you as a member is enough. You set this thing in motion. Active or not, I would rather not remove you, unless you insist.

**Comment by mitm001** [comment]
Transition is now complete, thanks for supporting the change David.
