### ISSUE TITLE
Link not working in `Controlling Game Logic > Application States`

### ISSUE THREAD

**Issue by Ledmington** [jMonkeyEngine/wiki#163]
In [this section](https://wiki.jmonkeyengine.org/docs/3.4/core/app/state/application_states.html#code-samples) the link to `BulletAppState` does not work.
It pointed to the package `jme3-bullet` which I think now is called `jme3-jbullet`, so the new link should be [this](https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-jbullet/src/main/java/com/jme3/bullet/BulletAppState.java).

**Comment by Ali-RS** [comment]
Fixed, thanks for reporting the issue.
