### ISSUE TITLE
a macro to link source & javadoc

### ISSUE THREAD

**Issue by davidB** [jMonkeyEngine/wiki#47]
The doc include link to source, sample, javadoc.
Suggestions: providing a macro to to generate the link. (easier to manage if relocation,...)

**Comment by mitm001** [comment]
I see why things were linked to the source file now. Hadn't thought about it moving, which seems likely one day.

**Comment by mitm001** [comment]
This is now fixed with an global attribute `link-javadoc` in the wiki-playbook.
