### ISSUE TITLE
Create standalone folder for localization documents

### ISSUE THREAD

**Issue by jmecn** [jMonkeyEngine/wiki#84]
Hi monkeys.

I'm planning to create a standalone folder for localization documents, such as: docs/asciidoc/zh-Hans-CN

I'm going to move all Chinese translation docs ( like `jme3_zh.adoc`) to that folder, and **work in my fork**. After my work finished, I will make a pr to jMonkeyEngine/wiki master. On the premise that the existing documents are not affected( except all `*_zh.adoc` docs).

@mitm001 @Ali-RS What do you think about my idea?

**Comment by mitm001** [comment]
I cant find the thread but the jist of it is that the wiki should not be used for storing multiple translations.

We can put a link to your fork gh-pages under the language topic in the main page and it should work exactly like the wiki.
https://jmonkeyengine.github.io/wiki/#languages

I was planning to remove all other language's sometime this year as well as some dead stuff like atomix.

**Comment by jmecn** [comment]
I never thought about storing all the docs in my own repo, but for me it sounds quite resonable. Maybe I should create another repo other than "jmecn/wiki", so I can still contribute to orgin wiki through it.

I agree on remove the Chinese translation in origin wiki repo.

Edit:
I have already create a new repo [jmecn/wiki](https://github.com/jmecn/jmecn-wiki). Below are some pages generated by travis-ci.

Home Page: 

* Origin: https://jmonkeyengine.github.io/wiki/
* Translation: http://jmecn.github.io/wiki/

Atom Editor:

* Origin: https://jmonkeyengine.github.io/wiki/wiki/atom_editor.html
* Translation: http://www.jmecn.net/wiki/wiki/atom_editor.html

Edit#2:
I renamed my fork from `jmecn/wiki` to `jmecn/origin_wiki`, and renamed `jmecn/jmecn-wiki` to `jmecn/wiki`.

**Comment by mitm001** [comment]
That looks really good. Let us know when you are ready to link it or just do a P/R if you do it yourself.

**Comment by jmecn** [comment]
I just make a PR. 

https://github.com/jMonkeyEngine/wiki/pull/85

**Comment by jmecn** [comment]
Thank you for merge my PR.

**Comment by mitm001** [comment]
NP, you got a lot of work ahead fixing those links. Are you using Atom editor?

**Comment by jmecn** [comment]
Yes. I use Atom for a while after reading [your post](https://hub.jmonkeyengine.org/t/new-wiki-editor/39291) in community.

ps: I think you have made a mistake on the order of section titles. They should be like this:

    == Downloading the Sources
    == Atom Editor Setup

Am I wrong?

**Comment by mitm001** [comment]
They are correct order because you first need a fork of the wiki. The wording could be better though since I can see how it would be confusing.

Should probably be called Prerequisites or something like that now that you point it out. 

Edit: Reason its first is that you need the fork info to setup the Editor after install.

**Comment by mitm001** [comment]
Changed it. Thanks for input.
