### ISSUE TITLE
Articles without reference

### ISSUE THREAD

**Issue by Andry2017** [jMonkeyEngine/wiki#91]
There are articles on the wiki that are not referenced. Perhaps they should be transferred to the main lessons page and updated.
[Physics : SoftBody](https://wiki.jmonkeyengine.org/jme3/advanced/softbody.html)
[Bullet Physics Pitfalls](https://wiki.jmonkeyengine.org/jme3/advanced/bullet_pitfalls.html)

**Comment by Ali-RS** [comment]
Added them to 
**Documentation for Advanced Users -> Physics Integration** 
Thanks for reporting @Andry2017  :)
