### ISSUE TITLE
Articles without reference part 2

### ISSUE THREAD

**Issue by Andry2017** [jMonkeyEngine/wiki#92]
There are articles on the wiki that are not referenced. Perhaps they should be transferred to the main lessons page and updated or delete something.

[https://wiki.jmonkeyengine.org/jme3/blendswaparcade.html](https://wiki.jmonkeyengine.org/jme3/blendswaparcade.html)
[https://wiki.jmonkeyengine.org/jme3/hardware_compatibility_list.html](https://wiki.jmonkeyengine.org/jme3/hardware_compatibility_list.html)
[https://wiki.jmonkeyengine.org/jme3/materials.html](https://wiki.jmonkeyengine.org/jme3/materials.html)

[https://wiki.jmonkeyengine.org/jme3/user_examples/thirdpersoncamera.html](https://wiki.jmonkeyengine.org/jme3/user_examples/thirdpersoncamera.html)

[https://wiki.jmonkeyengine.org/jme3/intermediate/rolling_madness.html](https://wiki.jmonkeyengine.org/jme3/intermediate/rolling_madness.html)

[https://wiki.jmonkeyengine.org/jme3/contributions/particles.html](https://wiki.jmonkeyengine.org/jme3/contributions/particles.html)
[https://wiki.jmonkeyengine.org/jme3/contributions/particles/reference.html](https://wiki.jmonkeyengine.org/jme3/contributions/particles/reference.html)

[https://wiki.jmonkeyengine.org/jme3/advanced/appstatesdemo.html](https://wiki.jmonkeyengine.org/jme3/advanced/appstatesdemo.html)

**Comment by Ali-RS** [comment]
> https://wiki.jmonkeyengine.org/jme3/contributions/particles.html
> https://wiki.jmonkeyengine.org/jme3/contributions/particles/reference.html

Fixed broken links to videos in wiki page  and added a link to it in contribution page  : https://wiki.jmonkeyengine.org/jme3/contributions.html

**Comment by mitm001** [comment]
The only articles worth keeping are the two you linked @Ali-RS  but I personally think these contributions pages should be maintained by the original project creators on their own websites. We should put a disclaimer in the contributions page that the projects are the responsibility of the creators and can be stale because of their lack of interest in their own projects.

**Comment by Andry2017** [comment]
I posted these links so you decide what to do with them! And I think that on the page contributions there should be references to interesting developments of people. To make it easier for newcomers to find something interesting and useful for themselves made by the community.

> We should put a disclaimer in the contributions page that the projects are the responsibility of the creators and can be stale because of their lack of interest in their own projects.

Reasonably!

> but I personally think these contributions pages should be maintained by the original project creators on their own websites.

Then such projects should at least be mentioned in the contributions and there should be links to these sites. And I think that if the author is more convenient to lay out with you, then let him post it.

**Comment by mitm001** [comment]
> there should be links to these sites. 

Yes, that's what I was thinking to. Links only. Allowing these peoples personal projects into the wiki confuses people and makes them think they are supported by jme.

**Comment by Andry2017** [comment]
> Allowing these peoples personal projects into the wiki confuses people and makes them think they are supported by jme.

I think not everyone is comfortable doing articles on other sites. And they may be useful to someone, but will be lost over time. So you could just mark these pages as personal projects and not jme. I think it would be more correct. If the project is no longer working. No source code. That such articles can be deleted. Or make for such articles a section with non-working projects in case their authors appear and decide to revive them.

**Comment by mitm001** [comment]
The older wiki stuff like this is left as is usually. I have from time to time fixed issues with them but rarely delete anything. The articles you linked to are examples of things that add no value, with the exception of the particle stuff, and will be gone on my next push unless anyone objects.

**Comment by Andry2017** [comment]
OK!

**Comment by mitm001** [comment]
All broken links are now fixed in the new antora site. Will need to start a new issue if more are found later.
